# Generated by Django 4.2 on 2023-05-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='gps_flag',
            field=models.CharField(default='NO', max_length=3),
        ),
        migrations.AddField(
            model_name='task',
            name='obj_project',
            field=models.CharField(default='Project object(999)', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='obj_user',
            field=models.EmailField(default='bbbb@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.CharField(default='Task object(999)', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='period',
            field=models.CharField(default='03:33PM~06:33PM', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='thumbnail',
            field=models.ImageField(default='/static/project/06978508/tasks/31489155/', upload_to='static/project/06978508/tasks/31489155/'),
        ),
        migrations.AddField(
            model_name='task',
            name='type_task',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='weight',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='token',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(max_length=100),
        ),
    ]
