# Generated by Django 4.2 on 2023-05-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_task_cover_remove_task_email_remove_task_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='obj_project',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='obj_user',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='task',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='period',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_task',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='weight',
            field=models.JSONField(),
        ),
    ]
