# Generated by Django 4.2 on 2023-05-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_task_content_alter_task_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='thumbnail',
        ),
    ]
